### ISSUE TITLE
Opening a file that scratch can't handle hangs indefinitely.

### ISSUE THREAD

**Issue by TraumaD** [elementary/scratch#232]
I opened a .jpg in scratch in error and scratch crashed. The problem is that scratch tries to restore that session and hangs indefinitly before it asks if you want to force close.

I worked around this by finding the file it tries to open and deleting or renaming it.

To recreate this bug try to open an image in scratch.

**Comment by artemanufrij** [comment]
Maybe something like press CTRL on start would open Scratch without loading files.

**Comment by jeremypw** [comment]
There was a recent commit (https://github.com/elementary/scratch/commit/3c94a1e547d38e495d05ff9521330a41dcc19de5) intended to fix this.  Which version are using (stable or unstable)?  At the moment it is only in the daily repository.

**Comment by jeremypw** [comment]
OK, it seems that if there is an invalid file for opening in settings, then the app does hang.  The workaround is to edit  org.pantheon.scratch.settings to set the key open-files-view1 to default ([]).  The latest version should not have any further problem (unless settings is manually tweaked) because it will no longer save an invalid file in the settings.

**Comment by jeremypw** [comment]
Actually the app does not hang although the view is blank,  the toolbar buttons are active so you can load a document by pressing the relevant button.  However, it should show the welcome screen not a blank.

**Comment by TraumaD** [comment]
if you right click and open with scratch with no previous instance open it will never open for you to click on anything in the toolbar.

**Comment by jeremypw** [comment]
Hopefully there will soon be a fix.
