### ISSUE TITLE
When failing to open a big file (1 GB) Scratch gets stucked forever

### ISSUE THREAD

**Issue by febrezo** [elementary/scratch#81]
The point is that as Scratch remembers its status, it will keep on trying loading such file. It could be interesting to remember whether it got closed unexpectedly to let the user select whether he wants to reload the previous session to avoid this issue.

**Comment by AlkindiX** [comment]
It is a good idea to warn user before opening such a big file and loading must be seperated into another thread and user can interrupt it with a cancel button.

**Comment by J0Ar** [comment]
Just a extra note: This happens not only when you open a big file...but also when you open an unsupported file by mistake.

**Comment by matzipan** [comment]
@J0Ar  for opening unsupported files please open a new issue. I believe there was one already open for this, but I can't find it right now.

**Comment by J0Ar** [comment]
@matzipan
I mean, when you open a problematic file (too big, not supported, ...whatever), then you can't use Scratch anymore, because it remember and tries to reload the last file. Let's wait about the work from @AlkindiX :)

**Comment by matzipan** [comment]
Problematic file is a bit too vague. Issues need to be specific.

**Comment by J0Ar** [comment]
Sorry for my (maybe) bad english. I wanted to say, It's irrelevant which kind of 'problematic-'file...
because the problem is: 
The user can't use/open Scratch anymore after he tries to open a (maybe) unsupported file.
Scratch will stuck because of the saved last state....the only way is to open dconf-editor (org.pantheon.scratch.settings) and delete the entries of ''Files opened in the previously session of Scratch''

Ok...i will try to explain a little bit further:
Some time ago opened a .xpi-file and then Scratch hung up.
(now i know it can't open such files and it was my mistake, but Files-preview is showing such files as text-files and i thought it will work...look at Screenshot) 
![mozilla s xpi s looks like text files](https://user-images.githubusercontent.com/23266409/29996438-aba9c78e-8ffe-11e7-8f98-6007c00b9cdc.png)
Anyway, i closed the Scratch window and tried to reopen...but as you know, it didn't work.

I thought, the problem which is mentioned here is not about the 'too big file'...but about the way Scratch handles such 'problematic files', or not?
- maybe Scratch should ask in a simple way if it should open the last session or
 Scratch should recognize if a file did not load correctly and then ask to cancel the last state

**Comment by jeremypw** [comment]
Perhaps, like Files, Scratch should not add docs that failed to open to the list of docs to restore on restart,

**Comment by AlkindiX** [comment]
All of this problems are correct and happens to me when mistakenly open a huge binary file like 
'dd if=/dev/zero of=test.txt'

**Comment by matzipan** [comment]
Interesting that the icon confused you in thinking Scratch might open it.
Perhaps icon for unknown file types should be changed to better reflect
this.
